// WARNING: auto-generated by Makefile release target -- run 'make release' to update

package etorch

const (
	Version     = "v1.0.2"
	GitCommit   = "9889d0f" // the commit JUST BEFORE the release
	VersionDate = "2020-11-24 02:23" // UTC
)

