// WARNING: auto-generated by Makefile release target -- run 'make release' to update

package etorch

const (
	Version     = "v1.1.0rc"
	GitCommit   = "92b7a86"          // the commit JUST BEFORE the release
	VersionDate = "2020-10-26 10:33" // UTC
)
