// WARNING: auto-generated by Makefile release target -- run 'make release' to update

package etorch

const (
	Version     = "v1.0.6"
	GitCommit   = "0818323" // the commit JUST BEFORE the release
	VersionDate = "2021-02-11 14:30" // UTC
)

